### ISSUE TITLE
Fix binding address for webpack-dev-server

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars-frontend#17]
By default the webpack-dev-server binds to 127.0.0.1:8181.  This is fine for developing and testing on a local laptop, but for a real service it doesn't work so well.

There are a couple of ways to fix this:  One is to modify the start script in `package.json` to run webpack-dev-server with a `--host` parameter.  Another is to set module.exports.devServer.host in `webpack.config.js`.  I'm not sure which one of this is a more flexible mechanism.

Or...can we make a different start script?

**Comment by haniotak** [comment]
The dev server is meant for rapid local development, not production. The backend will bring up the web UI; it will pull in the frontend as a dependency and provide the web UI as a webjar.
