### ISSUE TITLE
Timezones in in reservation times

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars-frontend#47]
Reported by kpillay:

Consider including time zone in the time shown when locking a reservation.

Commentary:  This is important given that even among ESnet personnel we are in various timezones.  It's not clear if the timezones we show are the browser timezone or the server timezone, but getting this right is important for correct functionality.  That's probably more important than configurable timezone preferences, etc.

**Comment by bmah888** [comment]
https://www.xkcd.com/1883/ is relevant.

**Comment by haniotak** [comment]
closed as of 1.0.3
