### ISSUE TITLE
See endpoints on editing pipe screen when locked

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars-frontend#50]
When creating a new reservation, the Editing Pipe dialog allows one to edit the path and bandwidth parameters of a pipe.  When the pipe is "unlocked" we can see the pipe endpoints on the left side of the dialog where the bandwidth fields are.  When the pipe is locked, the pipe endpoints are replaced by "A to Z bandwidth" and "Z to A bandwidth'.  It's probably more useful to display the actual endpoints at all times, rather than just when the pipe is unlocked.

**Comment by haniotak** [comment]
fixed!
