### ISSUE TITLE
Options for bandwidth selection for a fixture don't take effect

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars-frontend#51]
In the bandwidth selection panel when adding a fixture to a new reservation, there's a drop down for setting the requested bandwidth "From text input...", "Same as..." or "Opposite of...".  The latter two options don't seem to have any effect (it appears that they should provide a way to reference some other fixture in the reservation, but they don't).

**Comment by haniotak** [comment]
closed at 1.0.3
