### ISSUE TITLE
Styling of items in Components pane of Details view

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars-frontend#56]
Seen on 1.0b4 of the UI:

The component pane of the details view has some odd styling.

1.  "General connection info", "Junctions & fixtures", and "Pipes" are all underlined as if they were hyperlinks but they're just static text.

2.  The names of connections, fixtures, and pipes are not underlined, yet they're clickable.

It seems unclear to me, just looking at the pane, what items in this pane are "active" and which are just static text.  (The only way to tell is to roll the cursor over the various items and see what happens to the cursor shape.)  It's possible it's just my own confusion.

**Comment by bmah888** [comment]
<img width="340" alt="screen shot 2018-01-11 at 1 57 11 pm" src="https://user-images.githubusercontent.com/6485757/34849693-1feb837c-f6d8-11e7-9424-2062f4499f89.png">

**Comment by haniotak** [comment]
all these components are actually clickable & show the appropriate pane in the Info display in the center when selected.

**Comment by bmah888** [comment]
See item number 1 in my original comment...the words "General connection info", "ID: Z6KC", "Junctions & Fixtures", and "Pipes" aren't clickable but they are highlighted in various ways that look like they should be.

**Comment by haniotak** [comment]
will change to bold instead of underlined style in 1.0.5
