### ISSUE TITLE
UI Feedback on Diagnostic, Build/Dismantle Controls

### ISSUE THREAD

**Issue by bmah888** [esnet/oscars-frontend#57]
Observed on UI 1.0-beta4:

There are various controls in the detail view to Build or Dismantle the circuits for a reservation, or to run Diagnostics on a router.  These controls don't give any feedback that they've actually been activated and that an operation is in progress.  This could lead to confusion, or to a user activating a control multiple times.

**Comment by haniotak** [comment]
closed with 1.0.10
