### ISSUE TITLE
The default VLAN and bw for additional fixtures should be the same as the first.

### ISSUE THREAD

**Issue by mitchell-es** [esnet/oscars-frontend#67]
Once the user has picked a VLAN on the first fixture, that value should be re-used if possible on all additional fixtures. The same is true for bandwidth. The most common usage scenarios is a point to point connection where people will want the same values on both sides. Having mis-matched fixtures on either end of a connection is probably going to be less desirable.

**Comment by haniotak** [comment]
additional: suggest for first fixture the lowest 'globally' available vlan
