### ISSUE TITLE
Path routing choices don't have what I want.

### ISSUE THREAD

**Issue by mitchell-es** [esnet/oscars-frontend#70]
The list of 'path mode' options aren't clear. One is fit to bandwidth, but isn't it always going to do that? And how do the three 'widest' options differ? In my case I'm trying to get a path from sr12-rt1 to mx960-rt2 which goes via mx960-rt1. Choosing a backup/alternate path seems like a likely thing for people to want but I don't see a choice for it.

**Comment by haniotak** [comment]
I'll add more documentation to the path controls for the next build & will in the future enable an "add a backup path" option. 

in short the options are:
