### ISSUE TITLE
NOC or Org Contact Field

### ISSUE THREAD

**Issue by mitchell-es** [esnet/oscars-frontend#99]
The user field recording who created the circuit is often not the actual user of the circuit. We need a method of adding contacts to use for support issues and notifications related to the circuit. Ideally we could link to ESDB org or contact information but at a minimum text fields allowing us to record email contact information.

**Comment by mitchell-es** [comment]
I'll add I'm not sure if this issue should be in the frontend or some other repo. I'll also add that this was identified as an issue in one of the 1.0 scope documents https://docs.google.com/document/d/1eY4y_ycp2qyCUXw4SpXddBHZp3TOfAIcZZlbRkI2cTg/edit# where it was identified as Issue #4. I'm not sure where it's identified in more recent documents though.

**Comment by haniotak** [comment]
agreed. the backend already has support for this. will be adding this functionality to the frontend in the next version (which should be the release one)

**Comment by haniotak** [comment]
closed with 1.0.10
